#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "tests/setup-jest-boilerplate" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi
