name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14.20
    steps:
      - uses: actions/checkout@v3
      - name: Check directory
        run: pwd && ls -la
      - name: Install node modules
        run: npm i -g npm@latest && npm i
      - name: Run tests
        run: npm test